### PR TITLE
type of Time.spotted column converted to datetime

### LINKED ISSUE #1: Convert datatype of column Time.Spotted from string object to DateTime object.

### PR DESCRIPTION
**Pull request by abhishek-pes**
closes #1

### CODE REVIEW

**Comment by jeff10joy** [comment]
!bounty 20

**Comment by abhishek-pes** [comment]
@jeff10joy  thanks a lot  for accepting 
but what is !bounty 20?

**Comment by jeff10joy** [comment]
> 
> 
> @jeff10joy thanks a lot for accepting
> but what is !bounty 20?

You have scored 20 points for solving the first issue, for further details about bounties head to our discord server.

**Comment by srujandeshpande** [comment]
!bounty 20

**Comment by jeff10joy** [comment]
!bounty 20

**Pull request merged**
